name: Test
on:
  push:
    branches: [main]
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        type: string
        default: ${{ github.ref }}
jobs:
  Lint:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
      - uses: jauntin/actions/docker-run-action@v1
        with:
          image: ghcr.io/jauntin/php-test-image:8.3
          options: -v ${{ github.workspace }}:/var/www/html
          run: |
            composer install &&
            parallel ::: 'vendor/bin/pint --test' 'vendor/bin/phpstan --no-interaction --no-ansi'
  test:
    strategy:
      fail-fast: true
      matrix:
        stability: [prefer-lowest, prefer-stable]
        laravel: [^12.0]
    runs-on: arc-runner-set
    name: L${{ matrix.laravel }} - ${{ matrix.stability }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
      - uses: jauntin/actions/docker-run-action@v1
        with:
          image: ghcr.io/jauntin/php-test-image:8.3
          options: -v ${{ github.workspace }}:/var/www/html
          run: |
            composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update &&
            composer update --${{ matrix.stability }} --prefer-dist --no-interaction &&
            vendor/bin/phpunit --coverage-text
